name: jrnl
adopt-info: jrnl
summary: Collect your thoughts and notes without leaving the command-line
description: |
  jrnl is a simple journal application for the command line.
  
  You can use it to easily create, search, and view journal entries. Journals are stored as human-readable plain text, and can also be encrypted using AES encryption.
  
license: GPL-3.0

base: core22
grade: stable
confinement: strict

apps:
  jrnl:
    command: jrnl
    environment:
      LC_ALL: C.UTF-8
      PYTHONPATH: $SNAP/usr/lib/python3/site-packages 
    plugs:
      - home

parts:
  jrnl:
    source: https://github.com/jrnl-org/jrnl
    source-type: git
    plugin: python
    python-packages:
      - jrnl
      - poetry
      
    override-pull: |      
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
