name: jrnl
adopt-info: jrnl
summary: Collect your thoughts and notes without leaving the command-line
description: |
  jrnl is a simple journal application for the command line.
  
  You can use it to easily create, search, and view journal entries. Journals are stored as human-readable plain text, and can also be encrypted using AES encryption.
  
license: GPL-3.0

base: core20
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

assumes:
  - command-chain  

apps:
  jrnl:
    command: bin/jrnl
    command-chain: 
      - bin/homeishome-launch     
    environment:
      LC_ALL: C.UTF-8
      GTK_USE_PORTAL=1
    plugs:
      - home
      - desktop

parts:
  jrnl:
    source: https://github.com/jrnl-org/jrnl
    source-type: git
    source-branch: release
    plugin: python
    python-packages:
      - jrnl
      - poetry
    
    build-packages:
      - glibc-source
    stage-packages:
      - vim
      - nano
      - emacs
      
    override-pull: |      
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"

  homeishome-launch:
    plugin: nil
    stage-snaps:
      - homeishome-launch 
